// Generated by gencpp from file robotics_cyton/cyton_move_single_joint.msg
// DO NOT EDIT!


#ifndef ROBOTICS_CYTON_MESSAGE_CYTON_MOVE_SINGLE_JOINT_H
#define ROBOTICS_CYTON_MESSAGE_CYTON_MOVE_SINGLE_JOINT_H

#include <ros/service_traits.h>


#include <robotics_cyton/cyton_move_single_jointRequest.h>
#include <robotics_cyton/cyton_move_single_jointResponse.h>


namespace robotics_cyton
{

struct cyton_move_single_joint
{

typedef cyton_move_single_jointRequest Request;
typedef cyton_move_single_jointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cyton_move_single_joint
} // namespace robotics_cyton


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotics_cyton::cyton_move_single_joint > {
  static const char* value()
  {
    return "72d8e1515109568f522880436505bc21";
  }

  static const char* value(const ::robotics_cyton::cyton_move_single_joint&) { return value(); }
};

template<>
struct DataType< ::robotics_cyton::cyton_move_single_joint > {
  static const char* value()
  {
    return "robotics_cyton/cyton_move_single_joint";
  }

  static const char* value(const ::robotics_cyton::cyton_move_single_joint&) { return value(); }
};


// service_traits::MD5Sum< ::robotics_cyton::cyton_move_single_jointRequest> should match
// service_traits::MD5Sum< ::robotics_cyton::cyton_move_single_joint >
template<>
struct MD5Sum< ::robotics_cyton::cyton_move_single_jointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotics_cyton::cyton_move_single_joint >::value();
  }
  static const char* value(const ::robotics_cyton::cyton_move_single_jointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotics_cyton::cyton_move_single_jointRequest> should match
// service_traits::DataType< ::robotics_cyton::cyton_move_single_joint >
template<>
struct DataType< ::robotics_cyton::cyton_move_single_jointRequest>
{
  static const char* value()
  {
    return DataType< ::robotics_cyton::cyton_move_single_joint >::value();
  }
  static const char* value(const ::robotics_cyton::cyton_move_single_jointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotics_cyton::cyton_move_single_jointResponse> should match
// service_traits::MD5Sum< ::robotics_cyton::cyton_move_single_joint >
template<>
struct MD5Sum< ::robotics_cyton::cyton_move_single_jointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotics_cyton::cyton_move_single_joint >::value();
  }
  static const char* value(const ::robotics_cyton::cyton_move_single_jointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotics_cyton::cyton_move_single_jointResponse> should match
// service_traits::DataType< ::robotics_cyton::cyton_move_single_joint >
template<>
struct DataType< ::robotics_cyton::cyton_move_single_jointResponse>
{
  static const char* value()
  {
    return DataType< ::robotics_cyton::cyton_move_single_joint >::value();
  }
  static const char* value(const ::robotics_cyton::cyton_move_single_jointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTICS_CYTON_MESSAGE_CYTON_MOVE_SINGLE_JOINT_H
