// Generated by gencpp from file robotics_cyton/cyton_enable_robot.msg
// DO NOT EDIT!


#ifndef ROBOTICS_CYTON_MESSAGE_CYTON_ENABLE_ROBOT_H
#define ROBOTICS_CYTON_MESSAGE_CYTON_ENABLE_ROBOT_H

#include <ros/service_traits.h>


#include <robotics_cyton/cyton_enable_robotRequest.h>
#include <robotics_cyton/cyton_enable_robotResponse.h>


namespace robotics_cyton
{

struct cyton_enable_robot
{

typedef cyton_enable_robotRequest Request;
typedef cyton_enable_robotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cyton_enable_robot
} // namespace robotics_cyton


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotics_cyton::cyton_enable_robot > {
  static const char* value()
  {
    return "cbdd2e9cd62c12dcd05983de0c95bf07";
  }

  static const char* value(const ::robotics_cyton::cyton_enable_robot&) { return value(); }
};

template<>
struct DataType< ::robotics_cyton::cyton_enable_robot > {
  static const char* value()
  {
    return "robotics_cyton/cyton_enable_robot";
  }

  static const char* value(const ::robotics_cyton::cyton_enable_robot&) { return value(); }
};


// service_traits::MD5Sum< ::robotics_cyton::cyton_enable_robotRequest> should match
// service_traits::MD5Sum< ::robotics_cyton::cyton_enable_robot >
template<>
struct MD5Sum< ::robotics_cyton::cyton_enable_robotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotics_cyton::cyton_enable_robot >::value();
  }
  static const char* value(const ::robotics_cyton::cyton_enable_robotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotics_cyton::cyton_enable_robotRequest> should match
// service_traits::DataType< ::robotics_cyton::cyton_enable_robot >
template<>
struct DataType< ::robotics_cyton::cyton_enable_robotRequest>
{
  static const char* value()
  {
    return DataType< ::robotics_cyton::cyton_enable_robot >::value();
  }
  static const char* value(const ::robotics_cyton::cyton_enable_robotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotics_cyton::cyton_enable_robotResponse> should match
// service_traits::MD5Sum< ::robotics_cyton::cyton_enable_robot >
template<>
struct MD5Sum< ::robotics_cyton::cyton_enable_robotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotics_cyton::cyton_enable_robot >::value();
  }
  static const char* value(const ::robotics_cyton::cyton_enable_robotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotics_cyton::cyton_enable_robotResponse> should match
// service_traits::DataType< ::robotics_cyton::cyton_enable_robot >
template<>
struct DataType< ::robotics_cyton::cyton_enable_robotResponse>
{
  static const char* value()
  {
    return DataType< ::robotics_cyton::cyton_enable_robot >::value();
  }
  static const char* value(const ::robotics_cyton::cyton_enable_robotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTICS_CYTON_MESSAGE_CYTON_ENABLE_ROBOT_H
