// Generated by gencpp from file robotics_cyton/cyton_move_single_jointResponse.msg
// DO NOT EDIT!


#ifndef ROBOTICS_CYTON_MESSAGE_CYTON_MOVE_SINGLE_JOINTRESPONSE_H
#define ROBOTICS_CYTON_MESSAGE_CYTON_MOVE_SINGLE_JOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotics_cyton
{
template <class ContainerAllocator>
struct cyton_move_single_jointResponse_
{
  typedef cyton_move_single_jointResponse_<ContainerAllocator> Type;

  cyton_move_single_jointResponse_()
    : outcome(false)  {
    }
  cyton_move_single_jointResponse_(const ContainerAllocator& _alloc)
    : outcome(false)  {
  (void)_alloc;
    }



   typedef uint8_t _outcome_type;
  _outcome_type outcome;





  typedef boost::shared_ptr< ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct cyton_move_single_jointResponse_

typedef ::robotics_cyton::cyton_move_single_jointResponse_<std::allocator<void> > cyton_move_single_jointResponse;

typedef boost::shared_ptr< ::robotics_cyton::cyton_move_single_jointResponse > cyton_move_single_jointResponsePtr;
typedef boost::shared_ptr< ::robotics_cyton::cyton_move_single_jointResponse const> cyton_move_single_jointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator1> & lhs, const ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator2> & rhs)
{
  return lhs.outcome == rhs.outcome;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator1> & lhs, const ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotics_cyton

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae2c330a9f424f14e6045b1c9d0a0d15";
  }

  static const char* value(const ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae2c330a9f424f14ULL;
  static const uint64_t static_value2 = 0xe6045b1c9d0a0d15ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotics_cyton/cyton_move_single_jointResponse";
  }

  static const char* value(const ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#response\n"
"bool outcome\n"
"\n"
;
  }

  static const char* value(const ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.outcome);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cyton_move_single_jointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotics_cyton::cyton_move_single_jointResponse_<ContainerAllocator>& v)
  {
    s << indent << "outcome: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.outcome);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTICS_CYTON_MESSAGE_CYTON_MOVE_SINGLE_JOINTRESPONSE_H
