// Generated by gencpp from file robotics_cyton/cyton_move_single_jointRequest.msg
// DO NOT EDIT!


#ifndef ROBOTICS_CYTON_MESSAGE_CYTON_MOVE_SINGLE_JOINTREQUEST_H
#define ROBOTICS_CYTON_MESSAGE_CYTON_MOVE_SINGLE_JOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotics_cyton
{
template <class ContainerAllocator>
struct cyton_move_single_jointRequest_
{
  typedef cyton_move_single_jointRequest_<ContainerAllocator> Type;

  cyton_move_single_jointRequest_()
    : joint_number(0)
    , position(0.0)
    , vel(0.0)
    , acc(0.0)  {
    }
  cyton_move_single_jointRequest_(const ContainerAllocator& _alloc)
    : joint_number(0)
    , position(0.0)
    , vel(0.0)
    , acc(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _joint_number_type;
  _joint_number_type joint_number;

   typedef double _position_type;
  _position_type position;

   typedef double _vel_type;
  _vel_type vel;

   typedef double _acc_type;
  _acc_type acc;





  typedef boost::shared_ptr< ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct cyton_move_single_jointRequest_

typedef ::robotics_cyton::cyton_move_single_jointRequest_<std::allocator<void> > cyton_move_single_jointRequest;

typedef boost::shared_ptr< ::robotics_cyton::cyton_move_single_jointRequest > cyton_move_single_jointRequestPtr;
typedef boost::shared_ptr< ::robotics_cyton::cyton_move_single_jointRequest const> cyton_move_single_jointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator1> & lhs, const ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_number == rhs.joint_number &&
    lhs.position == rhs.position &&
    lhs.vel == rhs.vel &&
    lhs.acc == rhs.acc;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator1> & lhs, const ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotics_cyton

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "264be7c2e3d365d44f401d374e5f5f40";
  }

  static const char* value(const ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x264be7c2e3d365d4ULL;
  static const uint64_t static_value2 = 0x4f401d374e5f5f40ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotics_cyton/cyton_move_single_jointRequest";
  }

  static const char* value(const ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"int32 joint_number\n"
"float64 position\n"
"float64 vel\n"
"float64 acc\n"
;
  }

  static const char* value(const ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_number);
      stream.next(m.position);
      stream.next(m.vel);
      stream.next(m.acc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cyton_move_single_jointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotics_cyton::cyton_move_single_jointRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.joint_number);
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
    s << indent << "vel: ";
    Printer<double>::stream(s, indent + "  ", v.vel);
    s << indent << "acc: ";
    Printer<double>::stream(s, indent + "  ", v.acc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTICS_CYTON_MESSAGE_CYTON_MOVE_SINGLE_JOINTREQUEST_H
