// Generated by gencpp from file robotics_cyton/cyton_move_all_joints.msg
// DO NOT EDIT!


#ifndef ROBOTICS_CYTON_MESSAGE_CYTON_MOVE_ALL_JOINTS_H
#define ROBOTICS_CYTON_MESSAGE_CYTON_MOVE_ALL_JOINTS_H

#include <ros/service_traits.h>


#include <robotics_cyton/cyton_move_all_jointsRequest.h>
#include <robotics_cyton/cyton_move_all_jointsResponse.h>


namespace robotics_cyton
{

struct cyton_move_all_joints
{

typedef cyton_move_all_jointsRequest Request;
typedef cyton_move_all_jointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cyton_move_all_joints
} // namespace robotics_cyton


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotics_cyton::cyton_move_all_joints > {
  static const char* value()
  {
    return "9e70ab60f9bda1c235d95bce9fc54eb5";
  }

  static const char* value(const ::robotics_cyton::cyton_move_all_joints&) { return value(); }
};

template<>
struct DataType< ::robotics_cyton::cyton_move_all_joints > {
  static const char* value()
  {
    return "robotics_cyton/cyton_move_all_joints";
  }

  static const char* value(const ::robotics_cyton::cyton_move_all_joints&) { return value(); }
};


// service_traits::MD5Sum< ::robotics_cyton::cyton_move_all_jointsRequest> should match
// service_traits::MD5Sum< ::robotics_cyton::cyton_move_all_joints >
template<>
struct MD5Sum< ::robotics_cyton::cyton_move_all_jointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotics_cyton::cyton_move_all_joints >::value();
  }
  static const char* value(const ::robotics_cyton::cyton_move_all_jointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotics_cyton::cyton_move_all_jointsRequest> should match
// service_traits::DataType< ::robotics_cyton::cyton_move_all_joints >
template<>
struct DataType< ::robotics_cyton::cyton_move_all_jointsRequest>
{
  static const char* value()
  {
    return DataType< ::robotics_cyton::cyton_move_all_joints >::value();
  }
  static const char* value(const ::robotics_cyton::cyton_move_all_jointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotics_cyton::cyton_move_all_jointsResponse> should match
// service_traits::MD5Sum< ::robotics_cyton::cyton_move_all_joints >
template<>
struct MD5Sum< ::robotics_cyton::cyton_move_all_jointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotics_cyton::cyton_move_all_joints >::value();
  }
  static const char* value(const ::robotics_cyton::cyton_move_all_jointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotics_cyton::cyton_move_all_jointsResponse> should match
// service_traits::DataType< ::robotics_cyton::cyton_move_all_joints >
template<>
struct DataType< ::robotics_cyton::cyton_move_all_jointsResponse>
{
  static const char* value()
  {
    return DataType< ::robotics_cyton::cyton_move_all_joints >::value();
  }
  static const char* value(const ::robotics_cyton::cyton_move_all_jointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTICS_CYTON_MESSAGE_CYTON_MOVE_ALL_JOINTS_H
