// Generated by gencpp from file robotics_cyton/Float64.msg
// DO NOT EDIT!


#ifndef ROBOTICS_CYTON_MESSAGE_FLOAT64_H
#define ROBOTICS_CYTON_MESSAGE_FLOAT64_H

#include <ros/service_traits.h>


#include <robotics_cyton/Float64Request.h>
#include <robotics_cyton/Float64Response.h>


namespace robotics_cyton
{

struct Float64
{

typedef Float64Request Request;
typedef Float64Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Float64
} // namespace robotics_cyton


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotics_cyton::Float64 > {
  static const char* value()
  {
    return "fdb28210bfa9d7c91146260178d9a584";
  }

  static const char* value(const ::robotics_cyton::Float64&) { return value(); }
};

template<>
struct DataType< ::robotics_cyton::Float64 > {
  static const char* value()
  {
    return "robotics_cyton/Float64";
  }

  static const char* value(const ::robotics_cyton::Float64&) { return value(); }
};


// service_traits::MD5Sum< ::robotics_cyton::Float64Request> should match
// service_traits::MD5Sum< ::robotics_cyton::Float64 >
template<>
struct MD5Sum< ::robotics_cyton::Float64Request>
{
  static const char* value()
  {
    return MD5Sum< ::robotics_cyton::Float64 >::value();
  }
  static const char* value(const ::robotics_cyton::Float64Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotics_cyton::Float64Request> should match
// service_traits::DataType< ::robotics_cyton::Float64 >
template<>
struct DataType< ::robotics_cyton::Float64Request>
{
  static const char* value()
  {
    return DataType< ::robotics_cyton::Float64 >::value();
  }
  static const char* value(const ::robotics_cyton::Float64Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotics_cyton::Float64Response> should match
// service_traits::MD5Sum< ::robotics_cyton::Float64 >
template<>
struct MD5Sum< ::robotics_cyton::Float64Response>
{
  static const char* value()
  {
    return MD5Sum< ::robotics_cyton::Float64 >::value();
  }
  static const char* value(const ::robotics_cyton::Float64Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotics_cyton::Float64Response> should match
// service_traits::DataType< ::robotics_cyton::Float64 >
template<>
struct DataType< ::robotics_cyton::Float64Response>
{
  static const char* value()
  {
    return DataType< ::robotics_cyton::Float64 >::value();
  }
  static const char* value(const ::robotics_cyton::Float64Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTICS_CYTON_MESSAGE_FLOAT64_H
