// Generated by gencpp from file robotics_cyton/Float64Response.msg
// DO NOT EDIT!


#ifndef ROBOTICS_CYTON_MESSAGE_FLOAT64RESPONSE_H
#define ROBOTICS_CYTON_MESSAGE_FLOAT64RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotics_cyton
{
template <class ContainerAllocator>
struct Float64Response_
{
  typedef Float64Response_<ContainerAllocator> Type;

  Float64Response_()
    {
    }
  Float64Response_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::robotics_cyton::Float64Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotics_cyton::Float64Response_<ContainerAllocator> const> ConstPtr;

}; // struct Float64Response_

typedef ::robotics_cyton::Float64Response_<std::allocator<void> > Float64Response;

typedef boost::shared_ptr< ::robotics_cyton::Float64Response > Float64ResponsePtr;
typedef boost::shared_ptr< ::robotics_cyton::Float64Response const> Float64ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotics_cyton::Float64Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotics_cyton::Float64Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace robotics_cyton

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotics_cyton::Float64Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotics_cyton::Float64Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotics_cyton::Float64Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotics_cyton::Float64Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_cyton::Float64Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_cyton::Float64Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotics_cyton::Float64Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robotics_cyton::Float64Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robotics_cyton::Float64Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotics_cyton/Float64Response";
  }

  static const char* value(const ::robotics_cyton::Float64Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotics_cyton::Float64Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::robotics_cyton::Float64Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotics_cyton::Float64Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Float64Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotics_cyton::Float64Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robotics_cyton::Float64Response_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTICS_CYTON_MESSAGE_FLOAT64RESPONSE_H
