// Generated by gencpp from file cute_msgs/Float64Array.msg
// DO NOT EDIT!


#ifndef CUTE_MSGS_MESSAGE_FLOAT64ARRAY_H
#define CUTE_MSGS_MESSAGE_FLOAT64ARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cute_msgs
{
template <class ContainerAllocator>
struct Float64Array_
{
  typedef Float64Array_<ContainerAllocator> Type;

  Float64Array_()
    : data()  {
    }
  Float64Array_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::cute_msgs::Float64Array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cute_msgs::Float64Array_<ContainerAllocator> const> ConstPtr;

}; // struct Float64Array_

typedef ::cute_msgs::Float64Array_<std::allocator<void> > Float64Array;

typedef boost::shared_ptr< ::cute_msgs::Float64Array > Float64ArrayPtr;
typedef boost::shared_ptr< ::cute_msgs::Float64Array const> Float64ArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cute_msgs::Float64Array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cute_msgs::Float64Array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cute_msgs::Float64Array_<ContainerAllocator1> & lhs, const ::cute_msgs::Float64Array_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cute_msgs::Float64Array_<ContainerAllocator1> & lhs, const ::cute_msgs::Float64Array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cute_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cute_msgs::Float64Array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cute_msgs::Float64Array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cute_msgs::Float64Array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cute_msgs::Float64Array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cute_msgs::Float64Array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cute_msgs::Float64Array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cute_msgs::Float64Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const ::cute_msgs::Float64Array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x788898178a3da2c3ULL;
  static const uint64_t static_value2 = 0x718461eecda8f714ULL;
};

template<class ContainerAllocator>
struct DataType< ::cute_msgs::Float64Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cute_msgs/Float64Array";
  }

  static const char* value(const ::cute_msgs::Float64Array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cute_msgs::Float64Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] data\n"
;
  }

  static const char* value(const ::cute_msgs::Float64Array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cute_msgs::Float64Array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Float64Array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cute_msgs::Float64Array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cute_msgs::Float64Array_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUTE_MSGS_MESSAGE_FLOAT64ARRAY_H
